### ISSUE TITLE
Prefixing Virus Names

### ISSUE THREAD

**Issue by dmb-ts** [kurobeats/clamav_db#1]
I'd love to test your clamav signatures, but it is difficult to distinguish your signatures from the already active ones - so I'd like to request a prefixing of your signature names. This allows spamassassin & Co to treat your signatures different and allows easier testing.

Thanks :)

**Comment by Oweoqi** [comment]
sure dude, this is a learning exp for me too, can you give me an example and I'll script it up!

**Comment by kurobeats** [comment]
I'll get onto it pronto!

**Comment by kurobeats** [comment]
Done! I hope they help.

**Comment by dmb-ts** [comment]
Thank you so much for that fast reply. It does work, but I think the general approach is to prefix the virus names with your own name or something, kind of like this guy: https://github.com/wmetcalf/clam-punch/blob/master/miscreantpunch099.ldb

But thanks, I activated your signatures on a test run, so far no hits yet :)
